#!/usr/bin/env ruby
module FieldMap990
  DESCRIPTION = <<-HEREDOC
  FieldMap990: copy of Propublica API fields:
    https://projects.propublica.org/nonprofits/api
    or IRS 990 field mappings:
    https://www.irs.gov/pub/irs-soi/12eofinextractdoc.xls
  HEREDOC
  module_function

  MAP_FORMNAME = {
    0 => '990',
    1 => '990EZ',
    2 => '990PF'
  }
  FORMTYPE = 'formtype'
  MAP_COMMON = { # Propublica's basic financial data, common to all 990/990EZ filings; may have *missing* data
    'ein' => 'EIN',
    'tax_prd_yr' => 'Tax Year',
    'tax_prd' => 'Tax period end',
    FORMTYPE => 'Form type filed',
    'totrevenue' => 'Total revenue',
    'totfuncexpns' => 'Total expenses',
    'totassetsend' => 'Total assets, end of year',
    'totliabend' => 'Total liabilities, end of year',
    'pct_compnsatncurrofcr' => 'Percent of expenses marked as "Compensation of current officers, directors, etc"'
  }
  MAP_990_COMMON = { # Common actual data fields from 990 (i.e. not Propublica's calculated ones)
    'ein' => 'EIN',
    'tax_prd_yr' => 'Tax Year',
    'tax_prd' => 'Tax Period End',
    FORMTYPE => 'Form Type Filed',
    'totcntrbgfts' => 'Contributions', # F9_01_REV_CONTR_TOT_CY, F990-PC-PART-01-LINE-08-CY
    'invstmntinc' => 'Investment Income', # F9_01_REV_INVEST_TOT_CY, F990-PC-PART-01-LINE-10-CY
    'totprgmrevnue' => 'Program Service Revenue', # F9_01_REV_PROG_TOT_CY, F990-PC-PART-01-LINE-09-CY
    'totrevenue' => 'Total Revenue', # F9_01_REV_TOT_CY, F990-PC-PART-01-LINE-12-CY
    'totfuncexpns' => 'Total Expenses', # F9_01_EXP_TOT_CY, F990-PC-PART-01-LINE-18-CY
    'totassetsend' => 'Total Assets', # F9_01_NAFB_TOT_ASSET_EOY, F990-PC-PART-01-LINE-20-EOY
    'totliabend' => 'Total Liabilities', # F9_01_NAFB_TOT_LIAB_EOY, F990-PC-PART-01-LINE-21-EOY
    'totnetassetend' => 'Net Assets' # F9_01_NAFB_TOT_EOY, F990-PC-PART-01-LINE-22-EOY
  }
  MAP_990EZ_COMMON = { # Common actual data fields from 990EZ (i.e. not Propublica's calculated ones)
    'ein' => 'EIN',
    'tax_prd_yr' => 'Tax Year',
    'tax_prd' => 'Tax Period End',
    FORMTYPE => 'Form Type Filed',
    'totcntrbs' => 'Contributions', # F9_01_REV_CONTR_TOT_CY_V2, F990-EZ-PART-01-LINE-01
    'othrinvstinc' => 'Investment Income', # F9_01_REV_INVEST_TOT_CY, F990-EZ-PART-01-LINE-04
    'prgmservrev' => 'Program Service Revenue', # F9_01_REV_PROG_TOT_CY, F990-EZ-PART-01-LINE-02
    'totrevnue' => 'Total Revenue', # F9_01_REV_TOT_CY, F990-EZ-PART-01-LINE-09
    'totexpns' => 'Total Expenses', # F9_01_EXP_TOT_CY, F990-EZ-PART-01-LINE-17
    'totassetsend' => 'Total Assets', # F9_01_NAFB_TOT_ASSET_EOY, F990-EZ-PART-02-LINE-25-EOY
    'totliabend' => 'Total Liabilities', # F9_01_NAFB_TOT_LIAB_EOY, F990-EZ-PART-02-LINE-26-EOY
    'totnetassetsend' => 'Net Assets' # F9_01_NAFB_TOT_EOY, F990-EZ-PART-01-LINE-21
  }
  MAP_990 = {
    'ein' => 'Employer Identification Number', # Form 990 Header
    'tax_pd' => 'Tax period', # Form 990 Header
    'subseccd' => 'Subsection code', # Form 990 Header
    'unrelbusinccd' => 'Unrelated business income question', # Form 990 Pt V Line 3a
    'initiationfees' => 'Initiation fees amount', # Form 990 Pt V Line 10a
    'grsrcptspublicuse' => 'Gross receipts amount', # Form 990 Pt V Line 10b
    'grsincmembers' => 'Gross income from members', # Form 990 Pt V Line 11a
    'grsincother' => 'Gross income from other sources', # Form 990 Pt V Line 11b
    'totcntrbgfts' => 'Total contributions', # Form 990 Pt VIII Line 1h(A)
    'totprgmrevnue' => 'Program service revenue', # Form 990 Pt VIII Line 2g(A)
    'invstmntinc' => 'Investment income', # Form 990 Pt VIII Line 3(A)
    'txexmptbndsproceeds' => 'Tax-exempt bond proceeds', # Form 990 Pt VIII Line 4(A)
    'royaltsinc' => 'Royalties', # Form 990 Pt VIII Line 5(A)
    'grsrntsreal' => 'Gross rents -- Real estate', # Form 990 Pt VIII Line 6a(i)
    'grsrntsprsnl' => 'Gross rents -- Personal property', # Form 990 Pt VIII Line 6a(ii)
    'rntlexpnsreal' => 'Rental expense -- Real estate', # Form 990 Pt VIII Line 6b(i)
    'rntlexpnsprsnl' => 'Rental expense -- Personal property', # Form 990 Pt VIII Line 6b(ii)
    'rntlincreal' => 'Net rent -- Real estate', # Form 990 Pt VIII Line 6c(i)
    'rntlincprsnl' => 'Net rent -- Personal property', # Form 990 Pt VIII Line 6c(ii)
    'netrntlinc' => 'Net rental income', # Form 990 Pt VIII Line 6d(A)
    'grsalesecur' => 'Gross sales -- Securities', # Form 990 Pt VIII Line 7a(i)
    'grsalesothr' => 'Gross sales -- Other assets', # Form 990 Pt VIII Line 7a(ii)
    'cstbasisecur' => 'Sales expense -- Securities', # Form 990 Pt VIII Line 7b(i)
    'cstbasisothr' => 'Sales expense -- Other assets', # Form 990 Pt VIII Line 7b(ii)
    'gnlsecur' => 'Net gain from sales -- Securities', # Form 990 Pt VIII Line 7c(i)
    'gnlsothr' => 'Net gain from sales -- Other assets', # Form 990 Pt VIII Line 7c(ii)
    'netgnls' => 'Sales of assets', # Form 990 Pt VIII Line 7d(A)
    'grsincfndrsng' => 'Gross fundraising', # Form 990 Pt VIII Line 8a
    'lessdirfndrsng' => 'Fundraising expenses', # Form 990 Pt VIII Line 8b
    'netincfndrsng' => 'Fundraising income', # Form 990 Pt VIII Line 8c(A)
    'grsincgaming' => 'Gross income from gaming', # Form 990 Pt VIII Line 9a
    'lessdirgaming' => 'Gaming expenses', # Form 990 Pt VIII Line 9b
    'netincgaming' => 'Gaming income', # Form 990 Pt VIII Line 9c(A)
    'grsalesinvent' => 'Gross sales of inventory', # Form 990 Pt VIII Line 10a
    'lesscstofgoods' => 'Cost of goods sold (inventory)', # Form 990 Pt VIII Line 10b
    'netincsales' => 'Income from sales of inventory', # Form 990 Pt VIII Line 10c(A)
    'miscrevtot11e' => 'Other revenue', # Form 990 Pt VIII Line 11e(A)
    'totrevenue' => 'Total revenue', # Form 990 Pt VIII Line 12(A)
    'compnsatncurrofcr' => 'Compensation of current officers, directors, etc ', # Form 990 Pt IX Line 5(A)
    'othrsalwages' => 'Other salaries and wages', # Form 990 Pt IX Line 7(A)
    'payrolltx' => 'Payroll taxes', # Form 990 Pt IX Line 10(A)
    'profndraising' => 'Professional fundraising fees', # Form 990 Pt IX Line 11e(A)
    'totfuncexpns' => 'Total functional expenses', # Form 990 Pt IX Line 25(A)
    'totassetsend' => 'Total assets -- eoy', # Form 990 Pt X Line 16(B)
    'txexmptbndsend' => 'Tax-exempt bond liabilities -- eoy', # Form 990 Pt X Line 20(B)
    'secrdmrtgsend' => 'Secured mortgages and notes payable -- eoy', # Form 990 Pt X Line 23(B)
    'unsecurednotesend' => 'Unsecured mortgages and notes payable -- eoy', # Form 990 Pt X Line 24(B)
    'totliabend' => 'Total liabilities -- eoy', # Form 990 Pt X Line 26(B)
    'retainedearnend' => 'Paid-in or capital surplus -- eoy', # Form 990 Pt X Line 32(B)
    'totnetassetend' => 'Total Net Assets -- eoy', # Form 990 Pt X Line 33(B)
    'nonpfrea' => 'Reason for non-PF status', # Schedule A Pt I Lines 1-11
    'gftgrntsrcvd170' => 'Gifts grants membership fees received (170)', # Schedule A Pt II Line 1(f)
    'txrevnuelevied170' => 'Tax revenues levied (170)', # Schedule A Pt II Line 2(f)
    'srvcsval170' => 'Services or facilities furnished by gov (170)', # Schedule A Pt II Line 3(f)
    'grsinc170' => 'Gross income from interest etc (170)', # Schedule A Pt II Line 8(f)
    'grsrcptsrelated170' => 'Gross receipts from related activities (170)', # Schedule A Pt II Line 12
    'totgftgrntrcvd509' => 'Gifts grants membership fees received (509)', # Schedule A Pt III Line 1(f)
    'grsrcptsadmissn509' => 'Receipts from admissions merchandise etc (509)', # Schedule A Pt III Line 2(f)
    'txrevnuelevied509' => 'Tax revenues levied (509)', # Schedule A Pt III Line 4(f)
    'srvcsval509' => 'Services or facilities furnished by gov (509)', # Schedule A Pt III Line 5(f)
    'subtotsuppinc509' => 'Subtotal total support (509)', # Schedule A Pt III Line 10c(f)
    'totsupp509' => 'Total support (509)' # Schedule A Pt III Line 13(f)
  }
  MAP_990EZ = {
    'ein' => 'Employer Identification Number', # 990-EZ Header
    'tax_pd' => 'Tax period', # 990-EZ Header
    'subseccd' => 'Subsection code', # 990-EZ Header
    'totcntrbs' => 'Contributions, gifts, grants, etc received', # 990-EZ Pt I Line 1
    'prgmservrev' => 'Program service revenue', # 990-EZ Pt I Line 2
    'duesassesmnts' => 'Membership dues and assessments', # 990-EZ Pt I Line 3
    'othrinvstinc' => 'Investment income', # 990-EZ Pt I Line 4
    'grsamtsalesastothr' => 'Gross amount from sale of assets ', # 990-EZ Pt I Line 5a
    'basisalesexpnsothr' => 'Cost or other basis and sales expenses', # 990-EZ Pt I Line 5b
    'gnsaleofastothr' => 'Gain or (loss) from sale of assets', # 990-EZ Pt I Line 5c
    'grsincgaming' => 'Gross income from gaming', # 990-EZ Pt I Line 6a
    'grsrevnuefndrsng' => 'Special events gross revenue', # 990-EZ Pt I Line 6b
    'direxpns' => 'Special events direct expenses', # 990-EZ Pt I Line 6c
    'netincfndrsng' => 'Special events net income (or loss)', # 990-EZ Pt I Line 6d
    'grsalesminusret' => 'Gross sales of inventory', # 990-EZ Pt I Line 7a
    'costgoodsold' => 'Less: cost of goods sold', # 990-EZ Pt I Line 7b
    'grsprft' => 'Gross profit (or loss) from sales of inventory', # 990-EZ Pt I Line 7c
    'othrevnue' => 'Other revenue - total', # 990-EZ Pt I Line 8
    'totrevnue' => 'Total revenue', # 990-EZ Pt I Line 9
    'totexpns' => 'Total expenses', # 990-EZ Pt I Line 17
    'totexcessyr' => 'Excess or deficit', # 990-EZ Pt I Line 18
    'othrchgsnetassetfnd' => 'Other changes in net assets', # 990-EZ Pt I Line 20
    'totassetsend' => 'Total assets e-o-y', # 990-EZ Pt II Line 25B
    'totliabend' => 'Total liabilities e-o-y', # 990-EZ Pt II Line 26B
    'totnetassetsend' => 'Total net worth e-o-y', # 990-EZ Pt II Line 27B
    'unrelbusincd' => 'Unrelated business income question', # 990-EZ Pt V Line 35a
    'initiationfee' => 'Initiation fees and capital contributions', # 990-EZ Pt V Line 39a
    'grspublicrcpts' => 'Gross receipts for public use of club facilities', # 990-EZ Pt V Line 39b
    'nonpfrea' => 'Reason for non-PF status', # Schedule A Pt I Lines 1-11
    'gftgrntrcvd170' => 'Gifts grants membership fees received (170)', # Schedule A Pt II Line 1(f)
    'txrevnuelevied170' => 'Tax revenues levied (170)', # Schedule A Pt II Line 2(f)
    'srvcsval170' => 'Services or facilities furnished by gov (170)', # Schedule A Pt II Line 3(f)
    'grsinc170' => 'Gross income from interest etc (170)', # Schedule A Pt II Line 8(f)
    'grsrcptsrelatd170' => 'Gross receipts from related activities (170)', # Schedule A Pt II Line 12
    'totgftgrntrcvd509' => 'Gifts grants membership fees received (509)', # Schedule A Pt III Line 1(f)
    'grsrcptsadmiss509' => 'Receipts from admissions merchandise etc (509)', # Schedule A Pt III Line 2(f)
    'txrevnuelevied509' => 'Tax revenues levied (509)', # Schedule A Pt III Line 4(f)
    'srvcsval509' => 'Services or facilities furnished by gov (509)', # Schedule A Pt III Line 5(f)
    'subtotsuppinc509' => 'Subtotal total support (509)', # Schedule A Pt III Line 10c(f)
    'totsupp509' => 'Total support (509)' # Schedule A Pt III Line 13(f)
  }
  MAP_990PF = {
    'ein' => 'EIN', # 990-PF Header
    'tax_prd' => 'Tax period', # 990-PF Header
    'eostatus' => 'EO Status Code', # n/a (IRS-Coded)
    'tax_yr' => 'SOI Year', # 990-PF Header
    'operatingcd' => 'Record code', # n/a (IRS-Coded)
    'assetcdgen' => 'Asset code', # Generated based on value of total assets
    'transinccd' => 'Income code', # Generated based on value of total gross receipts
    'subcd' => 'Subsection code', # n/a (IRS-Coded)
    'grscontrgifts' => 'Contributions received', # 990-PF Pt I Line 1, column (a)
    'intrstrvnue' => 'Interest revenue', # 990-PF Pt I Line 3, column (a)
    'dividndsamt' => 'Dividends', # 990-PF Pt I Line 4, column (a)
    'totexcapgn' => 'Net gain – sales of assets', # 990-PF Part IV, Line 2 > 0
    'totexcapls' => 'Net loss – sales of assets', # 990-PF Part IV, Line 2 < 0
    'grsprofitbus' => 'Gross profit', # 990-PF Pt I, Line 10c, column (a)
    'otherincamt' => 'Other income', # 990-PF Pt I, Line 11, column (a)
    'compofficers' => 'Compensation of officers', # 990-PF Pt I, Line 13, column (a)
    'contrpdpbks' => 'Contributions paid', # 990-PF Pt I, Line 25, column (a)
    'totrcptperbks' => 'Total revenue', # 990-PF Pt I, Line 12, column (a)
    'totexpnspbks' => 'Total expenses', # 990-PF Pt I, Line 26, column (a)
    'excessrcpts' => 'Net income less deficit', # 990-PF Pt I, Line 27a
    'totexpnsexempt' => 'Total expenses – exempt purpose', # 990-PF Pt I, Line 26, column (d)
    'netinvstinc' => 'Net investment income', # 990-PF Pt I, Line 27b
    'totaxpyr' => 'Total excise tax', # 990-PF Pt IV, Line 5
    'adjnetinc' => 'Adjusted net income', # 990-PF Pt I, Line 27c
    'totassetsend' => 'Total assets – e-o-y book value', # 990-PF Pt II, Line 16, column (b)
    'invstgovtoblig' => 'Investments in U.S. & state government obligations – e-o-y book value', # 990-PF Pt II, Line 10a, column (b)
    'invstcorpstk' => 'Investments in corporate stock – e-o-y book value', # 990-PF Pt II, Line 10b, column (b)
    'invstcorpbnd' => 'Investments in corporate bonds– e-o-y book value', # 990-PF Pt II, Line 10c, column (b)
    'totinvstsec' => 'Total investments in securities – e-o-y book value', # 990-PF Pt II, Lines 10a+10b+10c, column (b)
    'totliabend' => 'Total liabilities – e-o-y book value', # 990-PF Pt II, Line 23, column (b)
    'fairmrktvalamt' => 'Total assets – e-o-y fair market value ', # 990-PF Header, Item I
    'undistribincyr' => 'Undistributed income', # 990-PF Pt XIII, Line 6f, column (d)
    'cmpmininvstret' => 'Minimum investment return', # 990-PF Pt X, Line 6
    'sec4940notxcd' => '4940 – no tax', # 990-PF Pt VI, Line 1b not checked
    'sec4940redtxcd' => '4940 – 1 % tax', # 990-PF Pt VI, Line 1b checked
    'infleg' => 'Influence legislation question', # 990-PF Pt VII-A, Line 1a
    'contractncd' => 'Contraction question', # 990-PF Pt VII-A, Line 5
    'claimstatcd' => 'Claiming status question', # 990-PF Pt VII-A, Line 9
    'propexchcd' => 'Property exchange question', # 990-PF Pt VII-B, Line 1a(1)
    'brwlndmnycd' => 'Borrow lend money question', # 990-PF Pt VII-B, Line 1a(2)
    'furngoodscd' => 'Furnished goods question', # 990-PF Pt VII-B, Line 1a(3)
    'paidcmpncd' => 'Paid compensation question', # 990-PF Pt VII-B, Line 1a(4)
    'trnsothasstscd' => 'Transfer question', # 990-PF Pt VII-B, Line 1a(5)
    'agremkpaycd' => 'Agree to make pay question', # 990-PF Pt VII-B, Line 1a(6)
    'undistrinccd' => 'Undistributed income question', # 990-PF Pt VII-B, Line 2a
    'dirindirintcd' => 'Direct indirect interest question', # 990-PF Pt VII-B, Line 3a
    'invstjexmptcd' => 'Jeopardizing investments question', # 990-PF Pt VII-B, Line 4a
    'propgndacd' => 'Propaganda question', # 990-PF Pt VII-B, Line 5a(1)
    'excesshldcd' => 'Influence public election question', # 990-PF Pt VII-B, Line 5a(2)
    'grntindivcd' => 'Grant individual question', # 990-PF Pt VII-B, Line 5a(3)
    'nchrtygrntcd' => 'Non-charity grant question', # 990-PF Pt VII-B, Line 5a(4)
    'nreligiouscd' => 'Non-religious question', # 990-PF Pt VII-B, Line 5a(5)
    'grsrents' => 'Gross rents', # 990-PF Pt I, Line 5a, column (a)
    'costsold' => 'Cost-of-goods-sold', # 990-PF Pt I, Line 10b
    'totrcptnetinc' => 'Total receipts net investment income', # 990-PF Pt I, Line 12, column (b)
    'trcptadjnetinc' => 'Total receipts adjusted net income', # 990-PF Pt I, Line 12, column (c)
    'topradmnexpnsa' => 'Total operating and administrative expenses column a ', # 990-PF Pt I, Line 24, column (a)
    'topradmnexpnsb' => 'Total operating and administrative expenses column b ', # 990-PF Pt I, Line 24, column (b)
    'topradmnexpnsd' => 'Total operating and administrative expenses column d', # 990-PF Pt I, Line 24, column (d)
    'totexpnsnetinc' => 'Total expenses net investment income', # 990-PF Pt I, Line 26, column (b)
    'totexpnsadjnet' => 'Total expenses adjusted net income', # 990-PF Pt I, Line 26, column (c)
    'othrcashamt' => 'Cash non-interest-bearing – e-o-y book value', # 990-PF Pt I, Line 24, column (d)
    'mrtgloans' => 'Investments mortgage loans – e-o-y book value', # 990-PF Pt II, Line 12, column (b)
    'othrinvstend' => 'Other investments – e-o-y book value', # 990-PF Pt II, Line 13, column (b)
    'fairmrktvaleoy' => 'Total assets – e-o-y fair market value ', # 990-PF Pt II, Line 16, column (c)
    'mrtgnotespay' => 'Mortgage loans payable – e-o-y book value', # 990-PF Pt II, Line 21, column (b)
    'tfundnworth' => 'Total fund net worth – e-o-y book value', # 990-PF Pt II, Line 31, column (b)
    'invstexcisetx' => 'Excise tax on net investment income', # 990-PF Pt IV, Line 5
    'sect511tx' => 'Section 511 tax', # 990-PF Pt IV, Line 2
    'subtitleatx' => 'Subtitle A tax', # 990-PF Pt IV, Line 4
    'esttaxcr' => 'Estimated tax credit', # 990-PF Pt IV, Line 6a
    'txwithldsrc' => 'Tax withheld at source', # 990-PF Pt IV, Line 6b
    'txpaidf2758' => 'Tax paid with Form 2758 (filing extension)', # 990-PF Pt IV, Line 6c
    'erronbkupwthld' => 'Erroneous backup withholding credit amount', # 990-PF Pt IV, Line 6d
    'estpnlty' => 'Estimated tax penalty', # 990-PF Pt IV, Line 8
    'balduopt' => 'Balance due or overpayment', # 990-PF Pt IV, Line 9 or Line 10 - Balance due if positive; overpayment if negative
    'crelamt' => 'Credit elect amount', # 990-PF Pt IV, Line 11
    'tfairmrktunuse' => 'Fair market value of assets not used for charitable purposes ', # 990-PF Pt X, Line 1d
    'distribamt' => 'Distributable amount', # 990-PF Pt XI, Line 7 and Part XIII, Line 1, column (d)
    'adjnetinccola' => 'Adjusted net income column a', # 990-PF Pt XIV, Line 2a, column (a)
    'adjnetinccolb' => 'Adjusted net income column b', # 990-PF Pt XIV, Line 2a, column (b)
    'adjnetinccolc' => 'Adjusted net income column c', # 990-PF Pt XIV, Line 2a, column (c)
    'adjnetinccold' => 'Adjusted net income column d', # 990-PF Pt XIV, Line 2a, column (d)
    'adjnetinctot' => 'Adjusted net income total', # 990-PF Pt XIV, Line 2a, column (e)
    'qlfydistriba' => 'Qualifying distributions column a', # 990-PF Pt XIV, Line 2e, column (a)
    'qlfydistribb' => 'Qualifying distributions column b', # 990-PF Pt XIV, Line 2e, column (b)
    'qlfydistribc' => 'Qualifying distributions column c', # 990-PF Pt XIV, Line 2e, column (c)
    'qlfydistribd' => 'Qualifying distributions column d', # 990-PF Pt XIV, Line 2e, column (d)
    'qlfydistribtot' => 'Qualifying distributions total', # 990-PF Pt XIV, Line 2e, column (e)
    'valassetscola' => 'Value assets column a', # 990-PF Pt XIV, Line 3a(1), column (a)
    'valassetscolb' => 'Value assets column b', # 990-PF Pt XIV, Line 3a(1), column (b)
    'valassetscolc' => 'Value assets column c', # 990-PF Pt XIV, Line 3a(1), column (c)
    'valassetscold' => 'Value assets column d', # 990-PF Pt XIV, Line 3a(1), column (d)
    'valassetstot' => 'Value assets total', # 990-PF Pt XIV, Line 3a(1), column (e)
    'qlfyasseta' => 'Qualifying assets column a', # 990-PF Pt XIV, Line 3a(2), column (a)
    'qlfyassetb' => 'Qualifying assets column b', # 990-PF Pt XIV, Line 3a(2), column (b)
    'qlfyassetc' => 'Qualifying assets column c', # 990-PF Pt XIV, Line 3a(2), column (c)
    'qlfyassetd' => 'Qualifying assets column d', # 990-PF Pt XIV, Line 3a(2), column (d)
    'qlfyassettot' => 'Qualifying assets total', # 990-PF Pt XIV, Line 3a(2), column (e)
    'endwmntscola' => 'Endowments column a', # 990-PF Pt XIV, Line 3b, column (a)
    'endwmntscolb' => 'Endowments column b', # 990-PF Pt XIV, Line 3b, column (b)
    'endwmntscolc' => 'Endowments column c', # 990-PF Pt XIV, Line 3b, column (c)
    'endwmntscold' => 'Endowments column d', # 990-PF Pt XIV, Line 3b, column (d)
    'endwmntstot' => 'Endowments total', # 990-PF Pt XIV, Line 3b, column (e)
    'totsuprtcola' => 'Total support column a', # 990-PF Pt XIV, Line 3c(1), column (a)
    'totsuprtcolb' => 'Total support column b', # 990-PF Pt XIV, Line 3c(1), column (b)
    'totsuprtcolc' => 'Total support column c', # 990-PF Pt XIV, Line 3c(1), column (c)
    'totsuprtcold' => 'Total support column d', # 990-PF Pt XIV, Line 3c(1), column (d)
    'totsuprttot' => 'Total support total', # 990-PF Pt XIV, Line 3c(1), column (e)
    'pubsuprtcola' => 'Public support column a', # 990-PF Pt XIV, Line 3c(2), column (a)
    'pubsuprtcolb' => 'Public support column b', # 990-PF Pt XIV, Line 3c(2), column (b)
    'pubsuprtcolc' => 'Public support column c', # 990-PF Pt XIV, Line 3c(2), column (c)
    'pubsuprtcold' => 'Public support column d', # 990-PF Pt XIV, Line 3c(2), column (d)
    'pubsuprttot' => 'Public support total', # 990-PF Pt XIV, Line 3c(2), column (e)
    'grsinvstinca' => 'Gross investment income column a', # 990-PF Pt XIV, Line 3c(4), column (a)
    'grsinvstincb' => 'Gross investment income column b', # 990-PF Pt XIV, Line 3c(4), column (b)
    'grsinvstincc' => 'Gross investment income column c', # 990-PF Pt XIV, Line 3c(4), column (c)
    'grsinvstincd' => 'Gross investment income column d', # 990-PF Pt XIV, Line 3c(4), column (d)
    'grsinvstinctot' => 'Gross investment income total' # 990-PF Pt XIV, Line 3c(4), column (e)
  }
  MAP_FORMTYPE = {
    0 => MAP_990,
    1 => MAP_990EZ,
    2 => MAP_990PF
  }
  MAP_FORMTYPE_COMMON = {
    0 => MAP_990_COMMON,
    1 => MAP_990EZ_COMMON
  }
end
